export const studentArr = [
  {
    id: 1,
    name: "john smith doe",
    level: "hnd II",
    matric_no: "15/69/0000",
    medals: {
      first: 2,
      second: 3,
      third: 0,
    },
    imageGuessing: {
      played: 5,
      top3: 6,
      top10: 8,
      highestScore: 20,
      correctScore: 960,
      wrongAnswer: 300,
    },
    quizLadder: {
      played: 5,
      top3: 6,
      top10: 8,
      highestScore: 20,
      correctScore: 920,
      wrongAnswer: 300,
    },
  },
  {
    id: 2,
    name: "jane smith doe",
    level: "hnd II",
    matric_no: "15/69/9999",
    medals: {
      first: 1,
      second: 5,
      third: 2,
    },
    imageGuessing: {
      played: 6,
      top3: 5,
      top10: 9,
      highestScore: 18,
      correctScore: 990,
      wrongAnswer: 100,
    },
    quizLadder: {
      played: 5,
      top3: 6,
      top10: 8,
      highestScore: 20,
      correctScore: 920,
      wrongAnswer: 300,
    },
  },
  {
    id: 3,
    name: "Mike ross denver",
    level: "hnd II",
    matric_no: "15/69/1111",
    medals: {
      first: 6,
      second: 2,
      third: 1,
    },
    imageGuessing: {
      played: 5,
      top3: 6,
      top10: 8,
      highestScore: 20,
      correctScore: 1060,
      wrongAnswer: 300,
    },
    quizLadder: {
      played: 10,
      top3: 8,
      top10: 9,
      highestScore: 20,
      correctScore: 1200,
      wrongAnswer: 50,
    },
  },
  {
    id: 4,
    name: "harvey jnr specter",
    level: "hnd II",
    matric_no: "15/69/1111",
    medals: {
      first: 1,
      second: 1,
      third: 0,
    },
    imageGuessing: {
      played: 5,
      top3: 6,
      top10: 8,
      highestScore: 20,
      correctScore: 950,
      wrongAnswer: 200,
    },
    quizLadder: {
      played: 5,
      top3: 6,
      top10: 8,
      highestScore: 20,
      correctScore: 920,
      wrongAnswer: 300,
    },
  },
];
